model = "gpt-5-codex"
model_reasoning_effort = "medium"
experimental_use_rmcp_client = true

[projects."/Users/kazuki/github/airiscode"]
trust_level = "trusted"

[projects."/Users/kazuki/github/agiletec"]
trust_level = "trusted"

[projects."/Users/kazuki/github/SuperClaude_Framework"]
trust_level = "trusted"

[projects."/Users/kazuki/github/airis-mcp-gateway"]
trust_level = "trusted"

[projects."/Users/kazuki/github/mindbase"]
trust_level = "trusted"

[projects."/Users/kazuki/github/mkk"]
trust_level = "trusted"

[projects."/Users/kazuki/github/selfhosted-supabase-mcp"]
trust_level = "trusted"

[projects."/Users/kazuki/github/SuperClaude_Plugin"]
trust_level = "trusted"






[notice]
hide_full_access_warning = true





[mcp_servers.airis-mcp-gateway]
url = "http://gateway.localhost:9090/api/v1/mcp"
startup_timeout_sec = 20
tool_timeout_sec = 60
enabled = true
